// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6L57WqOno3K8H26a_TzXxSHGlm1u0URQ',
    appId: '1:464181900890:web:589ed9c14bd7d3dbaa4a63',
    messagingSenderId: '464181900890',
    projectId: 'elostaz-travel',
    authDomain: 'elostaz-travel.firebaseapp.com',
    storageBucket: 'elostaz-travel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMT4FIKTacWiyf5LzK5VS3oPtIlii5qVI',
    appId: '1:464181900890:android:0d5d4065e3d6bc14aa4a63',
    messagingSenderId: '464181900890',
    projectId: 'elostaz-travel',
    storageBucket: 'elostaz-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASv6HNq5XHMQDRidEJw-H6YkA5Y36__tQ',
    appId: '1:464181900890:ios:384f2e5f25729b09aa4a63',
    messagingSenderId: '464181900890',
    projectId: 'elostaz-travel',
    storageBucket: 'elostaz-travel.firebasestorage.app',
    iosBundleId: 'com.example.elostazTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASv6HNq5XHMQDRidEJw-H6YkA5Y36__tQ',
    appId: '1:464181900890:ios:384f2e5f25729b09aa4a63',
    messagingSenderId: '464181900890',
    projectId: 'elostaz-travel',
    storageBucket: 'elostaz-travel.firebasestorage.app',
    iosBundleId: 'com.example.elostazTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6L57WqOno3K8H26a_TzXxSHGlm1u0URQ',
    appId: '1:464181900890:web:72b9803cb7e695d2aa4a63',
    messagingSenderId: '464181900890',
    projectId: 'elostaz-travel',
    authDomain: 'elostaz-travel.firebaseapp.com',
    storageBucket: 'elostaz-travel.firebasestorage.app',
  );
}
